spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: stephenderrick98@gmail.com
    password: psijhjcucwhxfgys
    protocol: smtp
    tls: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true